services:
  - type: web
    name: demandpilot-ml
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: PORT
        value: 8000
      - key: PYTHON_VERSION
        value: 3.12.10
      - key: DATABASE_URL
        fromDatabase:
          name: demandpilot-db
          property: connectionString
